server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-wz966n236z2v96401eo.mysql.rds.aliyuncs.com:3306/xukang-pre?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: xk_pre
    password: xk-pre#a1b2c3

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml

xxl:
  job:
    admin:
      address: http://101.43.122.53:9080/xxl-job-admin
    accessToken:
    executor:
      appName: my-job-executor
      address:
      ip:
      port: 9999
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 30