CREATE TABLE `tb_shop` (
  `id` bigint(20) NOT NULL COMMENT '主键',
  `shop_name` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '' COMMENT '店铺名称(数字、中文，英文(可混合，不可有特殊字符)，可修改)、不唯一',
  `shop_type` tinyint(2) DEFAULT '1' COMMENT '店铺类型（1：加盟  2:直营 3:二级商户 ）',
  `shop_intro` varchar(200) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '店铺简介(可修改)',
  `shop_short` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT '' COMMENT '简称',
  `shop_acreage` int(10) DEFAULT NULL COMMENT '门店面积（平方米）',
  `shop_level` varchar(4) DEFAULT '0' COMMENT '门店等级（1 :A ,2: B）',
  `technical_rate` int(10) DEFAULT NULL COMMENT '技术服务费（10000,表示百分位）',
  `is_signing` tinyint(2) DEFAULT '0' COMMENT '是否签约（0：未签约，1：已签约）',
  `service_range` int(10) DEFAULT NULL COMMENT '门店服务范围（米）',
  `owner_account` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT '' COMMENT '店长（账户）',
  `mobile` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT '' COMMENT '店铺绑定的手机(门店申请人账号）用户账号',
  `password` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '用户账号密码',
  `shop_tel` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT '' COMMENT '店铺联系电话',
  `shop_lat` double(18,10) DEFAULT '0.0000000000' COMMENT '店铺所在纬度(可修改)',
  `shop_lng` double(18,10) DEFAULT '0.0000000000' COMMENT '店铺所在经度(可修改)',
  `shop_address` varchar(100) DEFAULT '' COMMENT '店铺详细地址',
  `shop_no` varchar(32) DEFAULT NULL COMMENT '门店编号（编号规则：6位编号，前2位为省份，后4位为顺序编码）',
  `shop_head` varchar(64) DEFAULT '' COMMENT '负责人名称',
  `head_mobile` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT '' COMMENT '手机号负责人（法人）',
  `no_since` int(10) DEFAULT '0' COMMENT '自增组装门店编号()',
  `province_id` varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT '' COMMENT '店铺所在省份（描述）',
  `city_id` varchar(11) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' COMMENT '店铺所在城市（描述）',
  `area_id` varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT '' COMMENT '店铺所在区域（描述）',
  `area_address` varchar(64) DEFAULT NULL COMMENT '门店所在区域地址',
  `shop_logo` varchar(200) DEFAULT '' COMMENT '店铺logo(可修改)',
  `open_start_time` time DEFAULT NULL COMMENT '每天营业时间段 开始',
  `open_end_time` time DEFAULT NULL COMMENT '每天营业时间段 结束',
  `shop_status` tinyint(2) DEFAULT '1' COMMENT '店铺状态(-1:未开通 0: 停业中 1:营业中，2营业终止 4:待营业)，可修改',
  `audit_status` tinyint(4) NOT NULL DEFAULT '0' COMMENT '门店审核状态（1：提交审核，2：审核通过(包含银行审核)，3：审核驳回(包含银行审核)，9：待完善银行信息，10：平台审核通过，11：平台审核驳回，12：提交银行审核）',
  `audit_deputy` tinyint(4) DEFAULT '0' COMMENT '副审核流程状态（4：服务认证-提交,5：服务认证-驳回,6：服务认证-通过,7：规范认证-提交,8：规范认证-驳回,9：规范认证-通过,10：二、三审未提交）',
  `cooperation` tinyint(2) DEFAULT '0' COMMENT '门店合作状态(0:未开通 1:合作 2:终止)，可修改',
  `remark` varchar(255) DEFAULT NULL COMMENT '备注信息（审核备注：驳回）',
  `transport_type` tinyint(2) DEFAULT '0' COMMENT '0:商家承担运费; 1:买家承担运费',
  `receive_name` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '收件人名车',
  `receive_tel` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '收件人联系方式',
  `receive_province` varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '收件-省编号',
  `receive_city` varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '收件-市编号',
  `receive_area` varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '收件-区编号',
  `receive_address` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '收件-详细地址',
  `create_uid` bigint(20) DEFAULT '0' COMMENT '创建人',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_uid` bigint(20) DEFAULT '0' COMMENT '修改人',
  `update_time` datetime DEFAULT NULL COMMENT '修改时间',
  `reject_type` varchar(255) DEFAULT '' COMMENT '驳回图片或视频类型',
  `shop_certificate` tinyint(4) DEFAULT '0' COMMENT '门店证件类型（0：三证合一，1：营业执照，-1:无），默认：0',
  `default_bank` tinyint(4) DEFAULT '0' COMMENT '默认银行',
  `business_number` varchar(64) DEFAULT '' COMMENT '营业执照编号',
  `Identity_number` varchar(32) DEFAULT '' COMMENT '身份证编号',
  `have_read` tinyint(4) DEFAULT '0' COMMENT '是否已读协议（默认已读0，未读1）',
  `receive_region` varchar(32) DEFAULT '' COMMENT '收件区域结构',
  `settle_submit_time` datetime DEFAULT NULL COMMENT '入驻提交时间',
  `service_submit_time` datetime DEFAULT NULL COMMENT '服务认证提交时间',
  `signboard_submit_time` datetime DEFAULT NULL COMMENT '店招认证提交时间',
  `error_submit_time` datetime DEFAULT NULL COMMENT '移到异常时间',
  `sys_remark` varchar(255) DEFAULT NULL COMMENT '系统备注',
  `remove_reason` varchar(255) DEFAULT NULL COMMENT '移动异常门店原因',
  `error_flag` int(2) DEFAULT '0' COMMENT '是否异常门店：0=否,1=是',
  `wait_del_flag` int(2) DEFAULT '0' COMMENT '是否待删除：0=否,1=是',
  `issue_account` bigint(20) NOT NULL DEFAULT '0' COMMENT '发放金额 单位：分',
  `issue_status` tinyint(3) DEFAULT '0' COMMENT '发放状态(0未发放 1 待发放 2 已发放)',
  `issue_submit_time` datetime DEFAULT NULL COMMENT '发放提交时间',
  `issue_uid` bigint(20) DEFAULT '0' COMMENT '发放人',
  `issued_time` datetime DEFAULT NULL COMMENT '发放时间',
  `insurance_period` tinyint(1) DEFAULT '0' COMMENT '保险所处时期 0 测试期, 1 缓冲期, 2 正常期, 3 关闭期, 默认0',
  `insurance_update_time` datetime DEFAULT NULL COMMENT '保险所处时期变更时间',
  `invite_code` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT '' COMMENT '拓展人员邀请码【拓展端取邀请码，会员端，门店端和骑手端取用户id】',
  `industry_id` bigint(20) DEFAULT '0' COMMENT '行业id',
  `shipment_number` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT '' COMMENT '物流编号',
  `app_code_audit` tinyint(1) DEFAULT '3' COMMENT 'app码审核状态：0 待审核；1 审核驳回；2 审核通过；3 待完善',
  `invite_channel_type` tinyint(2) DEFAULT NULL COMMENT '邀请渠道类型【1-会员端，2-门店端，3-骑手端，4-拓展端】',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_shop_short` (`shop_short`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT COMMENT='店铺表';

CREATE TABLE `tb_shop_sku` (
  `id` bigint(20) NOT NULL COMMENT '主键',
  `shop_id` bigint(20) DEFAULT '0' COMMENT '门店ID，来自表tb_shop',
  `product_id` bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT '商品id，来自tb_product表',
  `product_category_id` bigint(20) DEFAULT '0' COMMENT '商品分类ID，来自表tb_product_category',
  `product_sn` varchar(50) DEFAULT '' COMMENT '商品编号',
  `sku_no` varchar(100) DEFAULT '' COMMENT 'SKU编码',
  `product_spec_id` bigint(20) DEFAULT NULL COMMENT '总控商品规格表主键ID',
  `spec` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT '' COMMENT 'sku规格，来自表tb_product_spec',
  `discount` decimal(12,0) DEFAULT '0' COMMENT '折扣=特价/零售价格',
  `sku_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '' COMMENT 'sku名称',
  `sku_desc` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT '' COMMENT 'sku描述',
  `market_price` bigint(20) DEFAULT '0' COMMENT '参考价，单位分',
  `discount_price` bigint(20) DEFAULT '0' COMMENT '特价=折扣价，单位分',
  `retail_price` bigint(20) DEFAULT '0' COMMENT '零售价格，单位分',
  `pic_url` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT '' COMMENT '产品主图url',
  `create_uid` bigint(20) DEFAULT '0' COMMENT '创建人',
  `update_uid` bigint(20) DEFAULT '0' COMMENT '修改人',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `sku_status` smallint(3) DEFAULT '0' COMMENT 'SKU状态(0上架，1下架 )',
  `product_channel_id` int(10) DEFAULT '0' COMMENT '商品频道,来自tb_product_channel.id',
  `sku_type` smallint(4) DEFAULT '0' COMMENT '商品类型 0:普通商品 1:特价商品 2:爆款商品 3 生活圈商品',
  `is_delete` smallint(3) DEFAULT '0' COMMENT '是否删除',
  `sales_number` int(8) DEFAULT '0' COMMENT '销量',
  `purchase_number` int(4) DEFAULT '0' COMMENT '特价商品限购数量，针对product_type=1',
  `hot_price` bigint(20) NOT NULL DEFAULT '0' COMMENT '爆款价格（单位分）',
  `vip_limit` int(4) NOT NULL DEFAULT '1' COMMENT '会员限购数',
  `shop_limit` int(8) NOT NULL DEFAULT '0' COMMENT '门店限购数',
  `batch_no` varchar(50) DEFAULT NULL COMMENT '批次号',
  `special_banner_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '特价商品banner主键ID,tb_special_banner.id',
  `is_system` tinyint(4) DEFAULT '0' COMMENT '生成方式：0 系统生成；1 自定义',
  `is_flag` tinyint(4) DEFAULT '0' COMMENT '是否标杆店设置 （0：否，1：是）',
  `top_flag` smallint(1) NOT NULL DEFAULT '0' COMMENT '是否置顶 0：否 1：是',
  `top_update_time` datetime DEFAULT NULL COMMENT '置顶更新时间',
  `category_label_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '店内分类标签id，对应tb_shop_category_label中的主键id',
  `life_audit_status` int(1) unsigned DEFAULT '1' COMMENT '生活圈商品审核状态,0 待审核;1审核成功;2审核驳回 ',
  `reason` varchar(255) DEFAULT NULL COMMENT '生活圈商品审核被驳回原因',
  `is_modify_image` tinyint(2) DEFAULT NULL COMMENT '生活圈商品是否需要修改图片，0=无，1=待修图，2=已修图',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `sipci` (`shop_id`,`product_category_id`),
  KEY `shop_id` (`shop_id`),
  KEY `category_label_id` (`category_label_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT COMMENT='门店商品';

